
language: objective-c
osx_image: xcode7.3
before_install:
  - gem install cocoapods --no-document # Since Travis is not always on latest version
  # - gem install xcpretty --no-document
script:
  # - set -o pipefail && xcodebuild -project WCCircularFloatingActionMenu.xcodeproj -scheme WCCircularFloatingActionMenu -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  # - pod lib lint
deploy:
  provider: script
  script: 
  - pod trunk push
  on:
    branch: master
    tags: true