
language: objective-c
osx_image: xcode7.3
# before_install:
# - gem install xcpretty --no-document
# script:
# - set -o pipefail && xcodebuild -project WCCircularFloatingActionMenu.xcodeproj -scheme WCCircularFloatingActionMenu -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
# - pod lib lint
deploy:
  provider: script
  script: scripts/push.sh
  skip_cleanup: true
  on:
    tags: true